### ISSUE TITLE
helper.rb does not read the region from config

### ISSUE THREAD

**Issue by lucjanrudziak** [shinesolutions/inspec-aem-aws#42]
In `'/library/helper.rb'` the `read_config` method does not copy the 'region' parameter from config to config_params.
https://github.com/shinesolutions/inspec-aem-aws/blob/master/libraries/helper.rb#L23

Bug:
Further down the line ruby_aem_aws expects the `:region` and, not finding it, sets the default region (ap-southeast-2), which breaks whatever's dependent on it.

**Comment by lucjanrudziak** [comment]
Closed by mistake.

**Comment by mbloch1986** [comment]
@lucjanrudziak 

thanks for reporting & the PR. You're right this needs to be fixed. 

We'll try to review it asap.

Cheers
@mbloch1986

**Comment by mbloch1986** [comment]
Fix included in release 1.10.0
